### PR TITLE
Added `notes` option to provide a path to the release notes

### PR DESCRIPTION
**Pull request by nitzanashi**
### `notes`

`string` - path

Optional. Path to Release notes file, it will take priority over changelog entries

### CODE REVIEW

**Comment by gotbahn** [comment]
why path and not a pure notes in md?

**Comment by nitzanashi** [comment]
> why path and not a pure notes in md?

You mean a string? We can not pass files in workflows

**Comment by gotbahn** [comment]
> > why path and not a pure notes in md?
> 
> You mean a string? We can not pass files in workflows

I mean why we would form a markdown, then read it, then take the needed entry if we can pass the needed entry as a string?

**Comment by nitzanashi** [comment]
> > > why path and not a pure notes in md?
> > 
> > 
> > You mean a string? We can not pass files in workflows
> 
> I mean why we would form a markdown, then read it, then take the needed entry if we can pass the needed entry as a string?

Becuase we already have this flow in [output](https://github.com/zattoo/output) So I didn't wanted to adjust the script, I can do it though if you prefer. I have no pref here

**Review by gotbahn — APPROVED** [review]

**Comment by nitzanashi** [comment]
Didn't squash -_- Sorrryyyyyy

**Comment by gotbahn** [comment]
ugh...

**Pull request merged**
